version: '3.8'

services:
  marcelapi:
    image: jnthnkabongo/marcel-api:latest
    container_name: marcelapi
    restart: always

    env_file:
      - .env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.marcelapi.rule=Host(`api.ergogroupeforce.org`)"
      - "traefik.http.routers.marcelapi.entrypoints=websecure"
      - "traefik.http.routers.marcelapi.tls=true"
      - "traefik.http.routers.marcelapi.tls.certresolver=letsencrypt"
      - "traefik.http.services.marcelapi.loadbalancer.server.port=80"

      # Redirection HTTP → HTTPS
      - "traefik.http.routers.marcelapi-http.rule=Host(`api.ergogroupeforce.org`)"
      - "traefik.http.routers.marcelapi-http.entrypoints=web"
      - "traefik.http.routers.marcelapi-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      
volumes:
  dbdata:

networks:
  web:
    external: true


